[general]
import = ["~/.config/alacritty/decay.toml"]


# Font
[font]
size = 10.5

[font.bold]
# family = "Iosevka Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "Iosevka Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "Iosevka Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "Iosevka Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Padding

[window]
padding = { x = 13, y = 13 }
dynamic_padding = true
